version: "3.6"
services:
  whoami:
    image: emilevauge/whoami
    networks:
      - traefik
    ports:
      - "80:80"
    deploy:
      replicas: 3
      labels:
        - "traefik.port=80"
        - "traefik.docker.network=traefik"
        - "traefik.frontend.rule=Host: test.awsl.me"
        - "traefik.backend.loadbalancer.sticky=true"

networks:
  traefik:
    external: true
